### ISSUE TITLE
New feature requested

### ISSUE THREAD

**Issue by cisnerosebastian** [dansingerman/jQuery-Browser-Language#1]
Nice and simple plugin. Thanks!
I think you should add a new function, a callback function that is executed when the information of the language is ready for use.
In my case, i needed to update some divs once the information about the browser language is ready.
Let me know if this is something you can do.
Thanks!

**Comment by dansingerman** [comment]
I think it already works that way:

```
<script>
    $.browserLanguage(function( language , acceptHeader ){
       // code to update divs here
    });
</script>
```
