### ISSUE TITLE
Simple request

### ISSUE THREAD

**Issue by Hlafordlaes** [dansingerman/jQuery-Browser-Language#3]
I really need this functionality, but am a n00b... horrid, I know. Over 60, too! Haven't programmed since the early '80s on a mini (PICK OS.) Sad case, I'm afraid.

Saw the examples on http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference, but have not had luck trying to use them

If you might kindly restate for me the lines to put in the header, and those for the body section, in order to use the plugin, it would really, really help.

For the body, instead of "nowDoSomethingWithIt(language);" perhaps a line that just outputs the language detected to the html would be very nice. I can hack things from there, hopefully.

FWIW, I have five subdomains that are language versions (en,es,fr,de,ca) of the same content, and am trying to redirect to the right language from the top level domain (users would be then allowed to switch among subdomains in case they object to the redirected language choice.)

Thanks so much in advance for any tips you might provide.

Hlaf.

**Comment by dansingerman** [comment]
Try this (anywhere in the page):

```
<script>
    $.browserLanguage(function( language , acceptHeader ){
      document.write("You have your browser language set to " + language);
    });
</script>
```
